(() => {
  'use strict';
  const COUNTY_ELECTIONS_URL = 'https://www.morriscountynj.gov/Departments/Elections';
  const NJ_ELECTIONS_URL = 'https://www.nj.gov/state/elections/';
  const source = (title, year, note='', url='') => ({ title, year, note, url });
  const MC_MANUAL = source('Morris County Poll Worker Manual — Election Day', '2024', '', COUNTY_ELECTIONS_URL);
  const BLUE = source('Morris County Voting Machine Manual — Election Day', '2023', '', COUNTY_ELECTIONS_URL);
  const NIGHT = source('Morris County Poll Worker End of Night Checklist', '2025', '', COUNTY_ELECTIONS_URL);
  const GUIDE1 = source('Morris County Poll Worker Info Guide #1 — Poll Worker Expectations', '2026', '', COUNTY_ELECTIONS_URL);
  const GUIDE2 = source('Morris County Poll Worker Info Guide #2 — Primary Election', '2026', '', COUNTY_ELECTIONS_URL);
  const GUIDE3 = source('Morris County Poll Worker Info Guide #3 — Reprinting vs Spoiling', '2026', '', COUNTY_ELECTIONS_URL);
  const GUIDE4 = source('Morris County Poll Worker Info Guide #4 — Wires and Setting Up', '2026', '', COUNTY_ELECTIONS_URL);
  const GUIDE5 = source('Morris County Poll Worker Info Guide #5 — Provisional Ballots', '2026', '', COUNTY_ELECTIONS_URL);
  const STATE = source('New Jersey District Board Member Training Manual', '2024', '', NJ_ELECTIONS_URL);

  window.MPW_CONTENT = {
    app: { contentVersion: '2026.08.17b', title: 'Master Poll Worker Guide', jurisdiction: 'New Jersey' },
    escalation: 'STOP — DO NOT GUESS. CONTACT THE BOARD OF ELECTIONS.',
    guideTopics: [
      { id:'checkin', title:'Standard Voter Check-In', modes:['early','election'], summary:'Preload the activation card, search for the correct voter, review the screen for flags, obtain the signature, and complete check-in once.', lessons:[
        ['preload','Preload activation card',['Before starting the voter check-in, physically confirm one blank activation card is loaded.','If a completed check-in does not print the activation card, use Reprint. Do not check the voter in again.']],
        ['search','Search for voter',['Start with the standard name search.','Expand the search when needed using additional letters, address or street, date of birth, or other available fields.','A failed first search does not mean the voter is unregistered.']],
        ['confirm','Confirm the voter record',['Ask the voter to state their information. Do not read information from the screen and ask the voter to agree.','When names are similar, confirm you have the correct person before continuing, including parent/child records or suffixes such as Jr. or Sr.']],
        ['flags','Read every flag',['Read the colored condition or flag first, then the red or green eligibility status bar, then read the gray instruction box completely.','Follow the gray instruction box and use the button it directs you to only after the instructions are understood.','Follow the screen over memory. If the screen does not clearly resolve the situation, stop and escalate.']],
        ['signature','Signature',['Have the voter sign and compare as directed.','Use Sign Again for an ordinary current signature mismatch.','No Signature on File is a separate provisional condition.']],
        ['reset','Complete check-in and prepare for the next voter',['File the signed Authority Slip in the designated signed Authority Slip bag.','Select Process Next Voter.','Preload one blank activation card for the next voter.']]
      ]},
      { id:'flag-reading', title:'Flagged Voter Screen', modes:['early','election'], summary:'Read the flagged-voter screen from top to bottom before taking action.', lessons:[
        ['order','Read in order',['Read the colored flag or condition first.','Read the red or green eligibility status bar.','Read the gray instruction box completely.','Follow the gray instruction box and select the voter-processing option it directs you to only after the instructions are understood.']]
      ]},
      { id:'worker-method', title:'Pilot / Co-Pilot Method', modes:['early','election'], summary:'Use two workers for a controlled read-and-do process.', lessons:[
        ['roles','Pilot / Co-Pilot',['The pilot reads the instructions.','The co-pilot performs the steps exactly as the pilot reads them.','Resolve disagreements privately, not in front of voters.']]
      ]}
    ],

    procedureCategories: [
      ['flags','ePollbook Flags'],['records','Forms & Record Changes'],['provisional','Provisional Ballots'],['mail','Vote-by-Mail'],['reprint','Reprint / Spoil'],['assistance','Voter Assistance'],['primary','Primary Election'],['equipment','Equipment / Troubleshooting'],['unusual','Unusual Situations']
    ],

    procedures: [
      { id:'normal', category:'flags', title:'Normal / No Flag', aliases:['regular voter','no flag'], modes:['early','election'], summary:'No special condition changes normal check-in.', steps:['Preload one blank activation card before starting the voter check-in.','Confirm the correct voter record.','Review the screen for flags.','Complete the voter signature.','Complete check-in once and prepare for the next voter.'], outcome:['No additional condition → Regular ballot.'], source:MC_MANUAL },
      { id:'affirm-address', category:'flags', title:'Affirm Address', aliases:['affirm','returned mail','residence'], modes:['early','election'], warning:'Do not ask for ID or proof of address solely because of an Affirm Address flag.', summary:'The voter must confirm whether the address on file is still current.', decision:{question:'Does the voter still live at the address shown?',yes:['Complete the lower Affirmation of Residence portion.','Voter signs.','Two poll workers from differing parties witness and sign.','Continue regular check-in if otherwise eligible.'],no:['Do not have the voter affirm the old address.','Use the Correction of Record / Changed Residence path.']}, steps:['Explain that Board of Elections mail was returned and the address must be confirmed.','Complete only the applicable portion of the combined form.','Return completed paperwork with the correct daily materials.'], outcome:['Same address / same district as applicable → Regular ballot after required form.','Moved → Ballot outcome follows Changed Residence.'], source:MC_MANUAL },
      { id:'id-required', category:'flags', title:'ID Required', aliases:['need id','active need id'], modes:['early','election'], warning:'Do not ask every voter for identification. Ask only when the voter record specifically requires it.', summary:'Record acceptable ID only when the ePollbook requires ID.', steps:['Ask for an acceptable identifying document only because the flag is present.','Record the ID category using the ePollbook prompt.','If acceptable ID is provided, continue regular check-in.','If ID is not provided, use the Not Provided path and process provisionally.'], outcome:['Acceptable ID recorded → Regular ballot.','ID not provided → Provisional ballot.'], source:MC_MANUAL },
      { id:'no-signature', category:'flags', title:'No Signature on File', aliases:['signature required','no signature'], modes:['early','election'], summary:'A missing stored signature is not the same as an ordinary signature mismatch.', steps:['Recognize the No Signature on File condition.','Process the voter by provisional ballot.','The Provisional Affirmation Statement supplies the signature for Board review/update.'], outcome:['No Signature on File → Provisional ballot.'], source:STATE },
      { id:'already-voted', category:'flags', title:'Already Voted', aliases:['voted already'], modes:['early','election'], summary:'The record shows the voter has already been credited with voting.', steps:['Explain the status shown.','If the voter accepts it, stop the check-in.','If the voter disputes it and wishes to vote, process a provisional ballot.','Document the incident when appropriate.'], outcome:['Accepts record → No additional ballot.','Disputes record → Provisional ballot.'], source:MC_MANUAL },
      { id:'early-voted', category:'flags', title:'Early Voted', aliases:['early voting already'], modes:['election'], summary:'The record shows Early Voting participation.', steps:['Explain the Early Voted status.','If the voter accepts it, stop the check-in.','If the voter disputes it and wishes to vote, process provisionally.'], outcome:['Disputes status → Provisional ballot.'], source:MC_MANUAL },
      { id:'not-found', category:'flags', title:'Voter Not Found', aliases:['not found','missing voter'], modes:['early','election'], critical:'DO NOT SELECT VOTER NOT FOUND UNLESS THE BOARD OF ELECTIONS DIRECTS YOU TO DO SO.', summary:'Search broadly, use lookup tools, then escalate before creating anything.', steps:['Recheck spelling and likely transcription errors.','Use the standard 3-and-3 search, then expand as needed.','Try address/street/date-of-birth or other available search fields.','Use District Lookup when appropriate.','Contact the Board of Elections.','Select Voter Not Found only if the Board directs you.'], outcome:['Board determination controls the next step.'], source:MC_MANUAL },
      { id:'changed-residence', category:'records', title:'Changed Residence', aliases:['moved','change address','address change'], modes:['early','election'], summary:'A move does not automatically mean provisional.', decision:{question:'Is the voter still within the same election district?',yes:['Complete the applicable Correction of Record information.','Continue with a regular ballot if otherwise eligible.'],no:['Determine the correct district/location.','A move to another district within the county generally requires provisional voting in the appropriate new district.','Outside-county or timing edge cases: call the Board.']}, steps:['Establish the voter’s current address from the voter.','Use the combined Correction of Record / Affirmation form as applicable.','Do not let the form itself dictate ballot type; the underlying move does.'], outcome:['Same election district → Regular ballot after correction.','Different district within the county → Provisional in appropriate new district.','Unclear/out-of-county edge case → Board determination.'], source:STATE },
      { id:'correction-record', category:'records', title:'Correction of Record', aliases:['correction','record update'], modes:['early','election'], summary:'Use the top Correction of Record portion for changed voter information.', steps:['Identify exactly what information is changing.','Complete only the applicable correction fields.','The Correction of Record documents the change; ballot type follows the underlying voter situation.','Return the form in the correct daily paperwork envelope.'], outcome:['Form records the change; it does not independently determine ballot type.'], source:MC_MANUAL },
      { id:'mail-in', category:'mail', title:'Mail-In Ballot Flag', aliases:['vote by mail','vbm','mail ballot'], modes:['early','election'], critical:'Do not process a Mail-In flagged voter as a regular machine voter.', summary:'A mail-in voter who chooses to vote in person votes provisionally.', steps:['Confirm the Mail-In flag.','Explain that an in-person vote must be provisional.','Process the voter provisionally.','If the voter wants removal from the vote-by-mail list, use Box 13 on the current Provisional Affirmation Statement.'], outcome:['Votes in person → Provisional ballot.'], source:GUIDE5 },
      { id:'provisional', category:'provisional', title:'Provisional Ballot', aliases:['provisional','orange bag'], modes:['early','election'], summary:'Complete the ePollbook provisional check-in, affirmation envelope, voting, sealing, return, and reconciliation.', steps:['Confirm provisional voting is the correct remedy.','In the ePollbook, choose Process Provisional and complete check-in.','No Authority Slip is issued for a provisional voter.','Direct the voter to the provisional table with the activation card and provisional materials.','Complete the Provisional Affirmation Statement envelope. Do not detach the flap/affirmation.','Direct the voter to the voting machine with the provisional activation card and provisional envelope to vote on the machine.','After voting, have the voter place the printed activation card/ballot into the provisional envelope while still within the voting-machine privacy area when possible, then remove the adhesive strip and seal the envelope.','Have the voter return the sealed provisional envelope to the poll worker.','Give the Notice to Provisional Ballot Voters and place the sealed envelope in the provisional bag.','At closing, all poll workers count voted provisionals, complete/sign the Inventory Sheet even if zero, and reseal the bag through the grommet and zipper.'], outcome:['Board of Elections adjudicates the provisional ballot.'], source:GUIDE5 },
      { id:'reprint', category:'reprint', title:'Reprint', aliases:['re-print','did not print','printer jam'], modes:['early','election'], critical:'DO NOT CHECK THE VOTER IN AGAIN.', summary:'Reprint a missing, misprinted, or damaged activation card or other output from a completed check-in.', steps:['Confirm the original check-in is already complete.','While the voter’s completed check-in is still on screen, use the on-screen Reprint path if it is available.','If the on-screen path is no longer available, use hamburger menu → Reprint.','Search for the completed voter check-in and select the voter.','Select the item to reprint: activation card, Authority Slip, assistance certificate, or other supported output.','Return to the normal workflow after the replacement prints.'], outcome:['The completed voter remains a single check-in.'], source:GUIDE3 },
      { id:'spoil', category:'reprint', title:'Spoil', aliases:['spoiled ballot','cancel ballot','no reissue'], modes:['early','election'], summary:'Spoil cancels an issued activation card/uncast ballot. It may begin at the machine or at check-in.', decision:{question:'Where is the voter when the spoil begins?',yes:['At machine: use the approved cancel/quit path with two workers as applicable, eject the activation card, and return it to check-in.'],no:['At check-in: if the voter received a card but never reached the machine and chooses not to vote, use the completed-check-in spoil path.']}, steps:['Use hamburger menu → Spoil.','Search for the voter and select the completed check-in.','Select the item/check-in to spoil and choose the applicable reason.','Select Reissue if the voter wants another ballot, or No Reissue if the check-in ends without another card.','For Reissue, preload a blank activation card before printing the replacement.','Do not remove the old Authority Slip; add the new Authority Slip produced for the reissue.','On the physical spoiled card, strike the printed ballot barcode with a strong vertical line, fold to the barcode, write SPOILED, and place it in the green spoiled/used-seal bag.'], outcome:['Reissue → Replacement activation card.','No Reissue → No replacement card is issued during that spoil action.'], source:GUIDE3 },
      { id:'assistance', category:'assistance', title:'Voter Assistance', aliases:['assist','assisted','assistance','assistor','help voter','booth assistance','assist form','certificate of assistance','substantial assistance'], modes:['early','election'], summary:'Record assistance during check-in when possible; use the completed-voter path when assistance becomes necessary afterward.', steps:['If assistance is known during active check-in, use More Options → Request Assistance.','Record the type of assistance and assistor information as required.','If the voter has no assistor and poll workers provide substantial assistance, two poll workers from differing parties assist.','If assistance becomes necessary after check-in, do not restart check-in; provide the necessary bipartisan assistance, then use the hamburger/completed-voter path to Request Assistance for that completed voter.','If the Certificate of Assistance fails to print, use Reprint rather than rechecking the voter in.'], outcome:['Voter receives only the assistance requested while ballot privacy is protected.'], source:MC_MANUAL },
      { id:'primary-party', category:'primary', title:'Primary Election — Party', aliases:['unaffiliated','una','democrat','republican','independent'], modes:['early','election'], summary:'In a primary election, Democratic and Republican ballots are tied to the voter’s recorded or declared party.', steps:['Affiliated Democratic or Republican voter: process the party shown; the activation card presents only that party’s ballot.','An affiliated voter’s party cannot be changed during check-in.','Unaffiliated (UNA) voter: use Declare Party; voter chooses Democratic or Republican and confirms.','Do not call UNA voters “Independent”; Independent is a separate off-party affiliation.','A voter affiliated with another party is not UNA and is not processed as though unaffiliated.','Do not use Voter Not Found to create a new record to bypass party affiliation.','For a future party change, provide the registration/party-change form or direct the voter to the available online voter-registration update option.'], outcome:['Affiliated/declared D or R → That party’s ballot only.','Off-party affiliation → Follow current primary guidance; do not issue provisional merely to vote another party’s primary.'], source:GUIDE2 },
      { id:'wrong-record', category:'unusual', title:'Wrong Voter Checked In / Wrong Record Used', aliases:['wrong record','family member','father son'], modes:['early','election'], critical:'STOP — CALL THE BOARD OF ELECTIONS.', summary:'Do not attempt to repair voter history locally.', steps:['Stop the check-in as soon as the problem is discovered.','Explain the exact record/voter mix-up to the Board.','Do not check another person in under the wrong record or attempt a local voter-history repair.','Follow the Board’s instructions and document as directed.'], outcome:['Board determines the record correction and voting remedy.'] },
      { id:'fleeing-voter', category:'unusual', title:'Fleeing Voter', aliases:['walked away','did not cast','left machine'], modes:['early','election'], summary:'A voter completed selections/printing but left before the final Cast step.', steps:['Confirm the machine remains active with the voter’s completed selections awaiting Cast.','Two poll workers from differing parties enter together.','Select Cast Vote.','Complete an Incident Report with machine number/count, what occurred, who responded, and the outcome.'], outcome:['Completed selections are cast under the bipartisan fleeing-voter procedure.'], source:BLUE },
      { id:'equipment-escalation', category:'equipment', title:'Equipment Escalation', aliases:['machine problem','printer problem','broken heart','warehouse'], modes:['early','election'], summary:'Use approved troubleshooting first, then escalate to the correct support path.', steps:['Voting-machine hardware abnormality → Machine Warehouse.','ePollbook, voter-record, printer, or voter-processing problem → Board of Elections.','If instructions direct you to call, stop there and call.','Do not improvise past an integrity-sensitive or unresolved equipment condition.'], outcome:['Support path controls the next action.'], source:MC_MANUAL }
    ],

    routines: [
      { id:'ev-opening', title:'Early Voting — Morning Opening', modes:['early'], summary:'Stage, verify, open, pair, train, and check accessibility before voters arrive.', phases:[
        {id:'stage',title:'Stage Equipment',steps:['Open the secured cage.','Stage white machine binders at matching machines and ePollbooks at matching stations.','Verify numbers before powering anything.','Memory: Stage — Don’t Start.']},
        {id:'machines',title:'Open Voting Machines',steps:['Compare the carried-forward numbered string seal on the media-access door.','Mismatch → stop and escalate.','Initial after verification; cut the verified seal and place it in the green used-seal bag.','Open media-access door with barrel key and verify the static tape seal over the media stick.','Power on, close door, remove key to red pouch.','Print System Readiness Report.','Two opposing-party workers review/initial; file in the correct day black pencil pouch.']},
        {id:'epb',title:'Open E-Poll Books',warning:'NO DRINKS OR LIQUIDS NEAR ELECTRONICS. NEVER UNPLUG ELECTION EQUIPMENT TO CHARGE A PERSONAL DEVICE.',steps:['Verify ePollbook and both printers match the station number.','Plug Lightning cable into the actual iPad charging port and power the strip; the unit should start.','Pair/test/save the matching Epson printer.','Pair/test/save the matching ExpressVote printer.','Set up one station at a time to avoid cross-connections.']},
        {id:'walkthrough',title:'Interface Walkthrough / Worker Training',steps:['Demonstrate scan/search, Launchpad tools, district lookup, reprint, spoil, assistance, directions, logout, and connectivity indicators.','Use pilot/co-pilot: pilot reads the instructions; co-pilot performs the steps.','Rotate workers through tasks; repetition builds muscle memory.']},
        {id:'day1',title:'Worker Login & Day 1 Report',steps:['About 10 minutes before opening, workers log in.','Only Day 1 of Early Voting generates the Poll Opening Report.','Day 1 Poll Opening Report goes in the Day 1 blue envelope for the runner.']},
        {id:'ada',title:'Accessibility & Polling Place',steps:['Confirm accessible parking/path and required clear area.','Maintain at least a five-foot area in front of the sign-in table and at least one voting machine in the district.','Place/test the accessibility bell where used and keep the receiver audible inside.','Correct or report any accessibility failure immediately.']}
      ]},
      { id:'ev-close', title:'Early Voting — Nightly Close', modes:['early'], critical:'DO NOT SELECT CLOSE POLL DURING AN ORDINARY INTERMEDIATE EARLY-VOTING NIGHT.', summary:'Exchange canisters, reseal, reconcile, sync, power down, and secure for tomorrow.', phases:[
        {id:'machines',title:'Voting Machines',steps:['Verify and record the media-access red string seal.','Remove the right-side red tape seal and place it on the daily index card.','Remove outgoing canister; verify red front seal; apply/record blue transport seal.','Transfer outgoing canister to runner.','Record replacement canister and blue seal, cut incoming blue seal to green used-seal bag, verify red front seal, insert/lock canister.','Apply new red tape panel seal.','Reports tab → required System Readiness Report → power down.']},
        {id:'epb',title:'E-Poll Books',steps:['Do not shut down all ePollbooks until the Master Poll Worker has required numbers/reconciliation.','Logout, Close for Day, allow sync, close app, unplug charging cable, power down, fold and secure.','Printers power down through the station power strip.']},
        {id:'paper',title:'Paperwork / Chain of Custody',steps:['Daily Early Voting paperwork goes in the correct blue envelope.','Complete transfer log with runner; split copies as required.','Runner takes sealed canisters/provisional materials as applicable.']},
        {id:'secure',title:'Secure Tomorrow',warning:'ROUTER SHUTS DOWN LAST.',steps:['Confirm every ePollbook has synced and powered down before disconnecting router.','Bring in accessibility bell, A-frames, and outdoor signs.','Return Chromebook/router and materials to secured cage.','Lock cage.']}
      ]},
      { id:'ed-opening', title:'Election Day — Opening', modes:['election'], summary:'Arrive at 5:00 AM and open for voters at 6:00 AM using the blue and green manuals.', phases:[
        {id:'arrive',title:'Arrive & Identify',steps:['Poll workers arrive by 5:00 AM.','Locate maroon materials bag, red bag, numbered machine key envelopes, manuals, and district materials.','Establish district responsibilities; in a shared room the lowest-numbered district owns the router.']},
        {id:'machines',title:'Open Voting Machines',warning:'Voting machines plug into a working wall outlet. Do not use the yellow extension reel. Maximum four machines daisy-chained per outlet.',steps:['Position and lock casters; place light stick vertical.','Cut white machine-cover seal; used seal to green bag; remove covers.','Match Key Envelope to machine number.','Open back compartment with barrel key and remove required materials.','Verify/cut red Top Access seal; used seal to green bag.','Plug into wall outlet and verify power lights.','Open Top Access, press red power button, close/lock and return key.','Enter Election Code/password from Key Envelope.','Verify Public Counter is zero.','Open Poll; two Zero Reports print automatically. Two opposite-party workers sign both; both go in Red Bag.','Install curtain rods/curtains and place needle/thread for authority slips.']},
        {id:'epb',title:'Set Up E-Poll Books',warning:'NO DRINKS OR LIQUIDS NEAR ELECTRONICS. NEVER UNPLUG ELECTION EQUIPMENT TO CHARGE A PERSONAL DEVICE.',steps:['Cut white ePollbook suitcase seal; used seal to green bag.','Remove Touchpad/ePollbook first, then heavier printers so the suitcase does not tip.','Match Touchpad, Epson, and ExpressVote numbers.','Lay out and wire stations before powering.','Power router early when assigned; use the Cradlepoint instructions.','Set up one numbered station at a time; test Epson and ExpressVote.','Verify location/district and connectivity; unresolved broken-heart status → call Board.','Login and place Poll Opening Report in Clear Envelope.']},
        {id:'paper',title:'Paperwork',steps:['Complete Payroll Voucher and Oath of Office.','Confirm required addresses, party, signatures, pickup/return-worker assignment and review initials.','Return signed paperwork to Clear Envelope.']},
        {id:'ada',title:'Accessibility / Signs / Final Readiness',steps:['Complete ADA accessibility walkthrough and checklist.','Confirm accessible parking, path, five-foot area at sign-in table, and at least one accessible voting machine.','Post required signs and establish official clock.','Confirm pens, styluses, cards, paper, printers, connectivity and clear paths.','Electioneering protected distance is 200 feet under current guidance.','Open polls at 6:00 AM.']}
      ], source:[BLUE, GUIDE4, GUIDE1] },
      { id:'ed-close', title:'Election Day — Closing', modes:['election'], summary:'After the last eligible voter has voted, close, reconcile, pack, and transfer in a controlled sequence.', phases:[
        {id:'closepolls',title:'Close Polls',steps:['At 8:00 PM, voters already in line may still vote.','Mark/control the last person in line so the line is not extended.','Do not close machines or ePollbooks until the final eligible voter has finished.','Slow is smooth. Smooth is fast. Use pilot/co-pilot and the manuals.']},
        {id:'machines',title:'Close Voting Machines',steps:['Open Poll/Device Status and use Election Code as directed.','Select Close Poll.','Three Results Reports print automatically, uncut. All poll workers sign all three.','Two Results Reports go in Red Bag; the district Judge takes the third.','A fourth public/challenger copy may be printed as local site practice.','Open Top Access; remove red media-stick tape to the Key Envelope index card.','Pull media stick straight up with two fingers—do not pull the string—and place it in the Small Yellow Media Stick Pouch.','Power Off → SHUT DOWN; close/lock Top Access.','Return screen vertical, cover machine, unplug/wrap cord, roll curtains/lower rods.','Remove used activation-card canister; secure with blue string seal and place in canister bag.','Return barrel key to Key Envelope; verify key/password index card and media pouch are in Red Bag.','Cover machine, light stick horizontal, unlock casters and return to secured location.']},
        {id:'epb',title:'Close E-Poll Books',steps:['Logout and use the Election Day close path in the green manual.','Allow all required syncing before app close/powerdown.','Close app, power down Touchpad/ePollbook, printers and pack using the diagram.','Keep router powered until every ePollbook in the physical room is synced, shut down and packed.']},
        {id:'provisional',title:'Provisional Reconciliation',steps:['All poll workers count voted provisional envelopes.','Complete and sign the Inventory Sheet even if there were zero provisionals.','Reseal the orange provisional bag through the grommet and zipper.']},
        {id:'materials',title:'Pack Materials',steps:['Use the current End of Night Checklist for exact destinations.','Authority Slips on Needle and Thread go in the Clear Envelope under the current checklist; this supersedes older blue-manual wording.','Do not guess County Clerk blue-bag contents; use its own checklist.']},
        {id:'transfer',title:'Final Transfer',warning:'ROUTER SHUTS DOWN LAST.',steps:['Lowest-numbered district in a shared room confirms all districts are clear before unplugging the router.','Return worker takes designated bags/ePollbook suitcase to the municipal return location and signs required chain-of-custody/return documentation.','Warehouse pickup of voting machines varies by municipality; follow local instructions.']}
      ], source:[BLUE, NIGHT, GUIDE5] }
    ],

    mpwSections: [
      {id:'first-round',title:'Election Day First Round',modes:['election'],items:['Before entering, check ADA parking/path and exterior conditions.','Review Payroll/Oath paperwork and worker assignments.','Ask how opening went; check ePollbook connectivity, printer supplies and any unresolved issues.','Brief workers on current Board reminders, electioneering, accessibility and unusual procedures.','While outside or during breaks, recheck electioneering protected zone, ADA route/parking and exterior signs.']},
      {id:'staffing',title:'Staffing & Room Management',modes:['early','election'],items:['Use the established site layout when it works; requirements first, flow second.','If a staffing shortage occurs, reassign available workers only when authorized.','Set the tone early and explain the plan before moving equipment.','Resolve worker disagreements privately; do not split the staff or argue in front of voters.','Same physical room = voting machines may be shared across districts. Different room = keep machines separate.']},
      {id:'integrity',title:'Integrity & Escalation',modes:['early','election'],critical:'STOP — DO NOT GUESS. CONTACT THE BOARD OF ELECTIONS.',items:['Use judgment for low-risk operational matters such as room flow and sign placement.','Do not use judgment to invent ballot eligibility, counting, record-history, seal, or chain-of-custody remedies.','If the procedure does not clearly resolve the situation, stop and call the Board.']},
      {id:'line-flow',title:'Line & Crowd Flow',modes:['early','election'],items:['Do not let voters form a long line in front of voting machines.','Queue voters at the ePollbook/check-in area and release them to machines as capacity becomes available.','Protect ADA paths and privacy while adjusting flow.']},
      {id:'incident',title:'Incident Reports',modes:['early','election'],items:['If something unusual occurs, document it; the Board decides what matters.','Record TIME / WHAT / ACTION / WHO / CALLS / OUTCOME.','Election Day incident reports go in the Clear Envelope; Early Voting uses the corresponding blue daily envelope.']}
    ],

    referenceSections: [
      {id:'accessibility',title:'Accessibility',modes:['early','election'],body:['At least one marked ADA parking space when off-street parking is provided.','Check van-accessible signage where applicable.','Path to the entrance and voting area must be free of major cracks, holes and obstructions.','Maintain at least a five-foot area in front of the sign-in table and at least one voting machine in the district.','Any failed accessibility check requires immediate correction/escalation under current instructions.']},
      {id:'electioneering',title:'Electioneering',modes:['early','election'],body:['Current Poll Worker Expectations states a 200-foot protected distance from the polling-place entrance and ballot drop box under P.L. 2025 c.92.','Poll workers remain politically neutral.','Escalate unresolved electioneering problems through the approved Board/law-enforcement path.']},
      {id:'challengers',title:'Challengers',modes:['early','election'],body:['Verify credentials/certificates.','Challengers do not question voters directly; challenges are made through the district board.','They may not handle election documents or approach voting-machine counters.','They may be positioned where they can hear announced voter names without interfering.','Refer unusual credential or conduct issues to the Board.']},
      {id:'media',title:'Media / Candidates / Exit Pollsters',modes:['early','election'],body:['Protect voter privacy and prevent interference.','Do not independently authorize media activity inside the polling room; refer media questions to the Board.','Candidates may vote or conduct legitimate business but may not campaign or create a photo-op in the protected area.','Authorized exit polling is voluntary and must not obstruct voters.']},
      {id:'two-hour',title:'Election Day Two-Hour Posting',modes:['election'],body:['Update the cumulative notice at 8 AM, 10 AM, noon, 2 PM, 4 PM and 6 PM.','Include machine votes plus provisional ballots.','Completed Cumulative 2 Hr Notice goes in the Clear Envelope at closing.']}
    ],

    endOfNight: {
      maroon:['Clear Envelope & Manila Envelope','2 Blue Containers','Green Spoiled/Used Seal Bag','Unused Styluses in bags','Yellow Signed Authority Slip Bag','Blue Tape','Activation Card Sleeves','Backup Authority Slips'],
      clear:['Signed Payroll & Oath – Red Cover','All signage – No Cell Phone, Electioneering, etc.','Blue & Green Manuals','Authority Slips on Needle and Thread','Filled Out Cumulative 2 Hr Notice','Filled Out Incident Reports','Filled Out Correction of Records/Affirm Address','Filled Out Mail-In Ballot Opt-out Forms','Voter Assistance Slips','Scissors'],
      manila:['Voter Complaint/Challenger Envelopes','Poll Worker Badges','All Unused Pads – Incident/Cumulative etc.','Magnifier','Pens','Unused Registrations','New Jersey State Manual','I Voted Stickers','Alcohol Wipes'],
      suitcase:['Unused Activation Cards (2)','Touchpads','Yellow Container (2)','Epson Printers & Cables','Extra Machine Paper Rolls (2)','ExpressVote Printers & Cables','Yellow Extension Reel & Power strip (2)','Charging cables','Bubble Wrapped Router','Unused extra paper rolls','Audio Device if used','Laminated Check-in Station Quick Reference Guide']
    },

    trainingTopics:['Opening and worker orientation','Numbered station setup','Activation-card preload','Standard voter check-in','Flagged voter screen','Mail-In Ballot','Already Voted / Early Voted','Voter Not Found','ID Required','Provisional ballots','Reprint','Spoil','Voter Assistance','Primary Election party handling','Crowd flow','Equipment escalation'],
    staticBoardQuestions:['Verify any current-year change to the exact selectable ID categories if the ePollbook software changes.','Confirm changed-residence timing/out-of-county edge cases when the current manual does not resolve them.','Confirm any current-year Early Voting closing checklist changes before hard-coding annual bag contents.'],
    currentLinks:[
      ['County Elections Website',COUNTY_ELECTIONS_URL],
      ['New Jersey Division of Elections',NJ_ELECTIONS_URL],
      ['New Jersey Election Law — Title 19','https://lis.njleg.state.nj.us/nxt/gateway.dll?f=templates&fn=default.htm&vid=Publish:10.1048/Enu']
    ],
    sources:[MC_MANUAL,BLUE,NIGHT,GUIDE1,GUIDE2,GUIDE3,GUIDE4,GUIDE5,STATE]
  };
})();
